confbook/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^meetingrooms/', include('meeting.urls', namespace='meeting')),
    url(r'^admin/', include(admin.site.urls)),
)

meeting/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
# from django.views.generic.simple import direct_to_template
from django.views.generic import FormView

urlpatterns = patterns('meeting.views',
    url(r'^agreed_list$', 'list_agreed_reservation', name="list_agreed_reservation"),
    url(r'^pending_list$', 'review_pending_reservation_list', name="review_pending_reservation_list"),
    url(r'^available_room_list$', 'list_available_room', name="list_available_room"),
    url(r'^booking/new$', 'new_reservation', name="new_reservation"),
    url(r'^success$', 'new_reservation', name="submit_success"),
    url(r'^reservation/(\d+)$', 'reservation_detail', name="reservation_detail"),
    url(r'^reservation/review/(\d+)$', 'review_pending_reservation', name="review_pending_reservation"),
    url(r'^reservation/(\d+)/delete$', 'delete_reservation', name="delete_reservation"),
    # url(r'^all$', 'list_meetingrooms', name="list_meetingrooms"),
    # url(r'^add$', 'add_meetingroom', name="add_meetingroom"),
    # url(r'^delete$', 'delete_meetingroom', name="delete_meetingroom"),
    )

meeting/models.py
# coding: utf-8
from django.db import models

# Create your models here.
class MeetingRoom(models.Model):
    # AVAILABLE = 0
    # OCCUPIED = 1
    # STATUS_CHOICE = (
    #     (AVAILABLE, 'Available'),
    #     (OCCUPIED, 'Occupied'),
    #     )
    name = models.CharField(max_length=128)
    # status = models.IntegerField(choices=STATUS_CHOICE, default=AVAILABLE)
    #floor = models.CharField(max_length=128)
    #capacity = models.IntegerField(default=0)
    
    def __unicode__(self):
        return self.name

class Contact(models.Model):
    name = models.CharField(max_length=64)
    phone = models.IntegerField(max_length=11, unique=True)
    dept = models.CharField(max_length=128)
    def __unicode__(self):
        return '%s, %s' % (self.name, self.phone)

class Reservation(models.Model):
    AM = 0
    PM = 1
    TIME_CHOICE = (
        (AM, 'AM'),
        (PM, 'PM'),
        )
    AVAILABLE_STATUS = 0
    PENDING_STATUS = 1
    AGREE_STATUS = 2
    STATUS_CHOICE = (
        (AGREE_STATUS, 'Agree'),
        (AVAILABLE_STATUS, 'Available'),
        (PENDING_STATUS, 'Pending'),
        )
    contact = models.ForeignKey(Contact)
    room = models.ForeignKey(MeetingRoom)
    book_date = models.DateField()
    book_time = models.IntegerField(choices=TIME_CHOICE, default=AM)
    subscribe_time = models.DateTimeField(auto_now_add=True)
    vip = models.CharField(max_length=256)
    count = models.IntegerField(max_length=3)
    status = models.IntegerField(choices=STATUS_CHOICE, default=AVAILABLE_STATUS)
    def __unicode__(self):
        return '%s, %s' % (self.contact.name, self.room.name)

meeting/forms.py
# coding: utf-8
from django import forms
from django.forms import ModelForm
from meeting import MeetingRoom

class MeetingRoomSaveForm(forms.Form):
    name = forms.CharField(
        widget = forms.TextInput(attrs={'size': 64})
        )

class BookRoomForm(forms.Form):
    name = forms.CharField(
        widget = forms.TextInput(attrs={'size': 64})
        )
    phone = forms.IntegerField(
        widget = forms.TextInput(attrs={'size': 11})
        )
    dept = forms.CharField(
        widget = forms.TextInput(attrs={'size': 128})
        )
    room = forms.CharField(
        widget = forms.SelectInput())
    date = forms.DateField(
        widget = forms.TextInput(initial=datetime.date.today)
        )

# class MeetingRoomSaveForm(ModelForm):
#     class Meta:
#         model = MeetingRoom
#         fields = ['name']
# class BookRoomForm(ModelForm):
#     class Meta:
#         model = Reservation
#         fields = ['name', 'room', 'book_date', 'book_time']

meeting/views.py
# coding: utf-8
from django.shortcuts import render
import time, datetime
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.core.context_processors import csrf
from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.auth.models import User
from django.template import RequestContext
from django.utils import simplejson
from django.core.urlresolvers import reverse
from meeting.models import *
import pdb

pdb.set_trace()
# I am common user, I want to book a meeting room
def _save_reservation(request):
    meetingroom = MeetingRoom.objects.get(name=request.POST['meetingroom'])
    person, created = Contact.objects.get_or_create(phone=request.POST['phone'])
    if created:
        person.name = request.POST['name']
        person.phone = request.POST['phone']
        person.dept = request.POST['dept']
        person.save()
    # rsv, c = Reservation.objects.get_or_create(pk=id)
    # if c:
    rsv = Reservation()
    rsv.contact = person
    rsv.room = meetingroom
    rsv.book_date = request.POST['date']
    rsv.book_time = request.POST['time_slot']
    rsv.vip = request.POST['vip']
    rsv.count = request.POST['count']
    rsv.status = Reservation.PENDING_STATUS
    # if not c:
    #     rsv.status = status
    rsv.save()
    # meetingroom.status = MeetingRoom.OCCUPIED
    # meetingroom.save()
    return rsv

def new_reservation(request):
    if request.method == 'POST':
        rsv = _save_reservation(request)
        return HttpResponseRedirect('/meetingrooms/agreed_list')
    if request.method == 'GET':
        meetingroom_id = request.GET.get('mid')
        meetingroom_name = request.GET.get('meetingroom')
        date = request.GET.get('date')
        time_slot = request.GET.get('time_slot')
        variables = RequestContext(request, {
            'meetingroom_id': meetingroom_id,
            'meetingroom_name': meetingroom_name,
            'date': date,
            'time_slot': time_slot,
            })
        return render_to_response('meeting/book_new_room.html', variables)

#---------- pending following functions-------------
# # I am admin, I want to add new meeting rooms
# def list_meetingrooms(request):
#     meetingrooms = MeetingRoom.objects.all()
#     variables = RequestContext(request, {
#         'meetingrooms': meetingrooms,
#         })
#     return render_to_response('meeting/room_list.html', variables)

# def add_meetingroom(request, id=None):
#     if request.GET.has_key('ajax'):
#         meetingroom, created = MeetingRoom.objects.get_or_create(pk=id)

# def delete_meetingroom(request, id=None):
#     mr = get_object_or_404(MeetingRoom, pk=id)
#     mr.delete()
#     results={'success': True}
#     json = simplejson.dumps(results)
#     # return HttpResponse()
#     # return HttpResponse(json, mimetype='application/json')
#     if request.is_ajax():
#         return HttpResponse(json, mimetype='application/json')
#     # else:
#     #     return HttpResponseRedirect('/user/%s/' % username)
#     # return HttpResponseRedirect(reverse('user_page', args=(username,)))
#     # return HttpResponseRedirect('/user/%s/' % username)
#---------------------the end-----------

    
# I am common user, I want to view someday's rooms
def list_agreed_reservation(request):
    # I am common user I want to view someday's meetings
    if 'date' in request.GET:
        date = request.GET.get('date')
    else:
        date = datetime.date.today
    rsvs = Reservation.objects.filter(
        status=Reservation.AGREE_STATUS,
        book_date=date)
    variables = RequestContext(request, {
        'rsvs': rsvs,
        })
    if request.GET.has_key('ajax'):
        return render_to_response('meeting/reservation_list.html', variables)
    else:
        return render_to_response('meeting/agreed_reservation_list.html', variables)

# I am admin I want to view booking requests list
def review_pending_reservation_list(request):
    if request.POST:
        id = request.POST["id"]
        rsv, c = Reservation.objects.get_or_create(pk=id)
    # if c:
    #     rsv.contact = person
    #     rsv.room = meetingroom
    #     rsv.book_date = request.POST['date']
    #     rsv.book_time = request.POST['time_slot']
    #     rsv.vip = request.POST['vip']
    #     rsv.count = request.POST['count']
    #     rsv.status = Reservation.PENDING_STATUS
        if not c:
            rsv.status = Reservation.AGREE_STATUS
        rsv.save()
        return HttpResponseRedirect('/meetingrooms/pending_list')

    if request.method=='GET':
        rsvs = Reservation.objects.filter(
            status=Reservation.PENDING_STATUS).order_by('-subscribe_time')
            # book_date=date).order_by('-subscribe_time')
        variables = RequestContext(request, {
            'rsvs': rsvs,
            })
        return render_to_response('meeting/pending_reservation_list.html', variables)

    

# I am common user I want to book someday's meeting room
def list_available_room(request):
    if 'date' in request.GET and 'time_slot' in request.GET:
        date = request.GET.get('date')
        time_slot = request.GET.get('time_slot')
    else:
        date = datetime.date.today
        time_slot = 0

    # bug: 需要列出从来没有预定过的会议室
    meetingrooms = MeetingRoom.objects.exclude(
        reservation__book_date=date, reservation__book_time=time_slot,
        reservation__status=Reservation.AGREE_STATUS).distinct()

    variables = RequestContext(request, {
        'meetingrooms': meetingrooms,
        })
    if request.GET.has_key('ajax'):
        return render_to_response('meeting/room_list.html', variables)
    else:
        return render_to_response('meeting/available_room_list.html', variables)

# I am common user, I want to view a reservation detail
def reservation_detail(request, id):
    reservation = get_object_or_404(Reservation, pk=id)
    variables = RequestContext(request, {
        'reservation': reservation
        })
    return render_to_response('meeting/reservation_detail.html', variables)

# I am admin, I want to check a reservation request
def review_pending_reservation(request, id):


    reservation = get_object_or_404(Reservation, pk=id)
    variables = RequestContext(request, {
        'reservation': reservation
        })
    return render_to_response('meeting/pending_reservation_detail.html', variables)

def delete_reservation(request, id=None):
    rsv = get_object_or_404(Reservation, pk=id)
    rsv.delete()
    results={'success': True}
    json = simplejson.dumps(results)
    if request.is_ajax():
        return HttpResponse(json, mimetype='application/json')
    else:
        return HttpResponseRedirect('/meetingrooms/pending_list')

meeting/templates/meeting/agreed_reservation_list.html
{% extends "meeting/base.html" %}

{% block header %}已排会议{% endblock %}

{% block body %}
<form class="form-inline" method="get" role="form" action="">
    <div class="form-group">
        <div class="col-sm-9">
            <input class="form-control" id="input_date" name="date" type="date" onchange="onDateTimeChange()" />
            <script type="text/javascript">
                var date = new Date();
                // $("#input_date").val(date);
                $("#input_date").val(date.getFullYear()+"-"+(date.getMonth()+1)+"-"+date.getDate());
                function onDateTimeChange () {
                    var date = $("#input_date").val();
                    var params = "?ajax&date=" + date;
                    $(".reservation_list").load(
                        document.URL + params
                    );
                    return false;}
            </script>
        </div>
    </div>
</form>
{% include "meeting/reservation_list.html" %}
<div class="col-sm-offset-2 col-sm-10">
    <a href="{% url 'meeting:list_available_room' %}" value="submit" role="button" class="btn btn-success list_room">预定</a>
    <!-- <a href="{% url 'meeting:list_available_room' %}?date=2014-10-10&time_slot=0" value="submit" role="button" class="btn btn-success">预定</a> -->
</div>
{% endblock %}

meeting/templates/meeting/available_room_list.html
{% extends "meeting/base.html" %}

{% block header %}可预订的会议室{% endblock %}
{% block body %}
    <form class="form-inline" method="get" role="form" action="">
        <div class="row">
            <div class="col-xs-9">
                <input class="form-control" id="input_date" name="date" type="date" onchange="onDateTimeChange()" />
            </div>
            <script type="text/javascript">
                var date = new Date();
                // $("#input_date").val(date);
                $("#input_date").val(date.getFullYear()+"-"+(date.getMonth()+1)+"-"+date.getDate());
                function onDateTimeChange () {
                    var date = $("#input_date").val();
                    var time_slot = $("#input_time_slot").val();
                    var params = "?ajax&date=" + date + "&time_slot=" + time_slot;
                    $(".meetingrooms_list").load(
                        document.URL + params
                    )}
            </script>
            <div class="col-xs-3">
                <select class="form-control" id="input_time_slot" name="time_slot" onchange="onDateTimeChange()" />
                    <option value='0'>上午</option>
                    <option value='1'>下午</option>
                </select>
            </div>
        </div>    
    </form>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <a name="back" href="{% url 'meeting:list_agreed_reservation' %}">返回</a>
        </div>
    </div>
    <!--available room list -->
{% include "meeting/room_list.html" %}
{% endblock %}

meeting/templates/meeting/base.html
{% extends "base.html" %}
{% block all_external %}
    <link rel="stylesheet" href="{{ STATIC_URL }}meeting/css/bootstrap.min.css">
    <script src="{{ STATIC_URL }}meeting/js/jquery-1.11.1.min.js"></script>
    <script src="{{ STATIC_URL }}meeting/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{{ STATIC_URL }}meeting/css/style.css">
{% endblock %}

meeting/templates/meeting/book_new_room.html
{% extends "meeting/base.html" %}
<div >预定
    {% block header %}{{ meetingroom_name }}{% endblock %}
</div>
{% block body %}
<form class="form-horizontal" method="post" role="form" action="">
    {% csrf_token %}
    <div class="date">
        <span class="day">{{ date }}</span><span class="time_slot">{{ time_slot }}</span>
    </div>
    <!-- <div class="form-group">
        <div class="col-sm-10">
            <input class="form-control date" id="disabledInput" name="count" type="number"
            placeholder="{{ time_slot }} {{ date }}" disabled>
        </div>
    </div> -->

    <div class="form-group">
        <label for="inputCount" class="col-sm-2 control-label">会议人数</label>
        <div class="col-sm-10">
            <input class="form-control" id="inputCount" name="count" type="number" />
        </div>
    </div>
    <div class="form-group">
        <label for="inputVip" class="col-sm-2 control-label">出席领导</label>
        <div class="col-sm-10">
            <input class="form-control" id="inputVip" name="vip" type="text" />
        </div>
    </div>
    <div class="form-group">
        <label for="inputDept" class="col-sm-2 control-label">主办单位</label>
        <div class="col-sm-10">
            <input class="form-control" id="inputDept" name="dept" type="text" />
        </div>
    </div>
    <div class="form-group">
        <label for="inputName" class="col-sm-2 control-label">联系人</label>
        <div class="col-sm-10">
            <input class="form-control" id="inputName" name="name" type="text" />
        </div>
    </div>
    <div class="form-group">
        <label for="inputPhone" class="col-sm-2 control-label">联系电话</label>
        <div class="col-sm-10">
            <input class="form-control" id="phone" name="phone" type="text" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button id="submit_pending" action="{% url 'meeting:new_reservation' %}" value="submit" type="submit" class="btn btn-success" onclick="checkLength()">
                提交</button>
            <a href="{% url 'meeting:list_available_room' %}" name="cancel" value="save as draft" class="btn btn-warning">
                取消</a>
        </div>
    </div>
</form>
<script type="text/javascript">
    var meetingroom = $(".page-title").text();
    var addMeetingRoom = '<input type="hidden" name="meetingroom" value='+meetingroom+'>';

    var date = $(".day").text();
    var addDate = '<input type="hidden" name="date" value='+date+'>';
    
    var time_slot = $(".time_slot").text();
    var addTimeSlot = '<input type="hidden" name="time_slot" value='+time_slot+'>';
    $("form").append(addMeetingRoom);
    $("form").append(addDate);
    $("form").append(addTimeSlot);
    
</script>
{% endblock %}

meeting/templates/meeting/book_room.html
{% extends "meeting/base.html" %}
{% block header %}预定会议室{% endblock %}
{% block body %}
<form class="form-horizontal" method="post" role="form" action="">
    {% csrf_token %}
    <div class="form-group">
        <label for="inputDate" class="col-sm-2 control-label">选择日期</label>
        <div class="col-sm-10">
            <input class="form-control" id="inputDate" name="date" type="date" />
        </div>
    </div>
    <div class="form-group">
        <label for="inputDate" class="col-sm-2 control-label">会议时间</label>
        <div class="col-sm-10">
            <input class="form-control" id="inputTime" name="time" type="radio" value="上午"/>
        </div>
        <div class="col-sm-10">
            <input class="form-control" id="inputTime" name="time" type="radio" value="下午"/>
        </div>
    </div>
    <div class="form-group">
        <label for="inputRoom" class="col-sm-2 control-label">会议室</label>
        <div class="col-sm-10">
            <select class="form-control" id="inputRoom" name="room"/>
                {% if meetingrooms %}
                    {% for meetingroom in meetingrooms %}
                        <option>{{ meetingroom }}</option>
                    {% endfor %}
                {% endif %}
            </select>
        </div>
    </div>
    <div class="form-group">
        <label for="inputDept" class="col-sm-2 control-label">主办单位</label>
        <div class="col-sm-10">
            <input class="form-control" id="inputDept" name="dept" type="text" />
        </div>
    </div>
    <div class="form-group">
        <label for="inputVip" class="col-sm-2 control-label">出席领导</label>
        <div class="col-sm-10">
            <input class="form-control" id="inputVip" name="vip" type="text" />
        </div>
    </div>
    <div class="form-group">
        <label for="inputName" class="col-sm-2 control-label">联系人</label>
        <div class="col-sm-10">
            <input class="form-control" id="inputName" name="name" type="text" />
        </div>
    </div>
    <div class="form-group">
        <label for="inputPhone" class="col-sm-2 control-label">联系电话</label>
        <div class="col-sm-10">
            <input class="form-control" id="inputPhone" name="phone" type="text" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button name="submit_pending" value="submit" type="submit" class="btn btn-success">
                <span class="glyphicon glyphicon-ok"></span> 提交</button>
            <button name="cancel" value="save as draft" type="submit" class="btn btn-warning">
                <span class="glyphicon glyphicon-remove"></span> 取消</button>
        </div>
    </div>
</form>
{% endblock %}

meeting/templates/meeting/pending_reservation_detail.html
{% extends "meeting/base.html" %}
{% block head %}会议详情{% endblock %}
{% block body %}
<ul class="list-group">
    <li class="list-group-item">
        <div class="room">{{ reservation.room.name }}</div>
    </li>
    <li class="list-group-item">
        <div class="date">{{ reservation.book_date|date:'Y-m-d' }}</div>
    </li>
    <li class="list-group-item">
        <div class="time_slot">{{ reservation.book_time }}</div>
    </li>
    <li class="list-group-item">
        <div class="vip">{{ reservation.vip }}</div>
    </li>
    <li class="list-group-item">
        <div class="count">{{ reservation.count }}</div>
    </li>
    <li class="list-group-item">
        <div class="dept">{{ reservation.contact.dept }}</div>
    </li>
    <li class="list-group-item">
        <div class="contact">{{ reservation.contact.name }}</div>
    </li>
    <li class="list-group-item">
        <div class="phone">{{ reservation.contact.phone }}</div>
    </li>
</ul>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button value="submit" type="submit" id="{{reservation.id}}" name="agree" action="{% url 'meeting:review_pending_reservation_list' %}" class="confirm post tool">确认预定</button>
        <a id="{{rsv.id}}" name="delete" href="{% url 'meeting:delete_reservation' reservation.id %}" class="post tool delete">拒绝预定</a>
    </div>
</div>
<script src="{{ STATIC_URL }}meeting/js/ajax.js"></script>
{% endblock %}

meeting/templates/meeting/pending_reservation_list.html
{% extends "meeting/base.html" %}
{% block header %}待处理的预定请求{% endblock %}
{% block body %}
<ul class="list-group">
    {% if rsvs %}
        {% for rsv in rsvs %}
        <ul class="list-inline">
            <li>
                <div class="pannel pannel-default">
                    <div class="pannel-heading">
                        <ul class="list-inline">
                            <li>
                                <div class="room">{{ rsv.room.name }}</div>
                            </li>
                            <li>
                                <div class="datetime">{{ rsv.subscribe_time }}</div>
                            </li>
                        </ul>
                    </div>
                    <div class="pannel-body">
                        <ul class="list-group">
                            <li>
                                <ul class="list-inline">
                                    <li>{{ rsv.vip }}</li>
                                    <li>{{ rsv.count }}</li>
                                </ul>
                            </li>
                            <li>{{ rsv.contact.name }}</li>
                            <li>{{ rsv.contact.phone }}</li>
                        </ul>
                    </div>
                </div>
            </li>
          <!-- control group -->
            <li>
                <a href="{% url 'meeting:review_pending_reservation' rsv.id %}" role="button">审批
            </li>
            </a>
        </ul>
        {% endfor %}
    {% else %}
        <p>没有会议！</p>
    {% endif %}
</ul>
{% endblock %}

meeting/templates/meeting/reservation_detail.html
{% extends "meeting/base.html" %}
{% block head %}会议详情{% endblock %}
{% block body %}
<ul class="list-group">
    <li class="list-group-item">
        <div class="room">{{ reservation.room.name }}</div>
    </li>
    <li class="list-group-item">
        <div class="date">{{ reservation.book_date|date:'Y-m-d' }}</div>
    </li>
    <li class="list-group-item">
        <div class="time_slot">{{ reservation.book_time }}</div>
    </li>
    <li class="list-group-item">
        <div class="vip">{{ reservation.vip }}</div>
    </li>
    <li class="list-group-item">
        <div class="count">{{ reservation.count }}</div>
    </li>
    <li class="list-group-item">
        <div class="dept">{{ reservation.contact.dept }}</div>
    </li>
    <li class="list-group-item">
        <div class="contact">{{ reservation.contact.name }}</div>
    </li>
    <li class="list-group-item">
        <div class="phone">{{ reservation.contact.phone }}</div>
    </li>
</ul>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <a href="{% url 'meeting:list_agreed_reservation' %}" >返回</button>
    </div>
</div>
<script src="{{ STATIC_URL }}meeting/js/ajax.js"></script>
{% endblock %}

meeting/templates/meeting/reservation_list.html
<div class="pannel-group reservation_list">
    <div class="bs-callout bs-callout-info">
        {% if rsvs %}
            <h4>上午已订：</h4>
            {% for rsv in rsvs %}
                {% if rsv.book_time == 0 %}
                    <div class="pannel pannel-default">
                        <div class="pannel-heading">
                            <ul class="list-inline">
                                <h4 class="pannel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#">
                                        <li>
                                            <a href="{% url 'meeting:reservation_detail' rsv.id %}" value="submit" class="btn btn-success">
                                                {{ rsv.room.name }}</a>
                                        </li>
                                    </a>
                                </h4>
                            </ul>
                        </div>
                        <div id="" class="pannel-collapse collapse in">
                            <div class="pannel-body">
                                <ul class="list-group">
                                    <li>
                                        <ul class="list-inline">
                                            <li>{{ rsv.vip }}</li>
                                            <li>{{ rsv.count }}</li>
                                        </ul>
                                    </li>
                                    <li>{{ rsv.contact.name }}</li>
                                    <li>{{ rsv.contact.phone }}</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% else %}
            <p class="meetingroom-name">上午没有会议！</p>
        {% endif %}
    </div>
    <div class="bs-callout bs-callout-warning">
        {% if rsvs %}
            <h4>下午已订：</h4>
            {% for rsv in rsvs %}
                {% if rsv.book_time == 1 %}
                    <div class="pannel pannel-default">
                        <div class="pannel-heading">
                            <ul class="list-inline">
                                <h4 class="pannel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#">
                                        <li>
                                            <a href="{% url 'meeting:reservation_detail' rsv.id %}" value="submit" class="btn btn-success">
                                                {{ rsv.room.name }}</a>
                                        </li>
                                    </a>
                                </h4>
                            </ul>
                        </div>
                        <div id="" class="pannel-collapse collapse in">
                            <div class="pannel-body">
                                <ul class="list-group">
                                    <li>
                                        <ul class="list-inline">
                                            <li>{{ rsv.vip }}</li>
                                            <li>{{ rsv.count }}</li>
                                        </ul>
                                    </li>
                                    <li>{{ rsv.contact.name }}</li>
                                    <li>{{ rsv.contact.phone }}</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% else %}
            <p class="meetingroom-name">下午没有会议！</p>
        {% endif %}
    </div>
</div>

meeting/templates/meeting/room_detail.html
{% extends "meeting/base.html" %}
{% block head %}会议室详情{% endblock %}

meeting/templates/meeting/room_list.html
<div class="meetingrooms_list">
{% if meetingrooms %}
    {% for meetingroom in meetingrooms %}
    <ul class="list-group">
        <!-- <div class="row"> -->
            <li class="list-group-item">
                <!-- <div id="{{ meetingroom.id }}" class="col-xs-9 mid"> -->
                    <h3 id="{{ meetingroom.id }}" class="mid">{{ meetingroom.name }}</h3>
                <!-- </div> -->
                <!-- <div class="col-xs-3"> -->
                    <button class="book_meeting" action="{% url 'meeting:new_reservation' %}"
                    class="btn btn-warning btn-book" type="submit">预定</button>
                <!-- </div> -->
            </li>
        <!-- </div> -->
    </ul>
    {% endfor %}
</div>
<script src="{{ STATIC_URL }}meeting/js/ajax.js"></script>
{% else %}
    <h2>没有可预订的会议室！</h2>
{% endif %}

meeting/templates/meeting/room_mgt.html
{% extends "meeting/base.html" %}

{% block header %}会议室管理{% endblock %}
{% block body %}
<script src="{{ STATIC_URL }}blog/js/delete.js"></script>

<ul class="opts list-inline">
    {% if meetingrooms %}
        {% for meetingroom in meetingrooms %}
        <!-- <ul class="opts list-inline"> -->
            <li>
              <div class="meetingroom">
                  <h2 class="meetingroom-name"><a href="/meetingrooms/{{ meetingroom.name }}">{{ meetingroom.name }}</a></h2>
                  <div class="meetingroom-meta" />
              </div>
            </li>
          <!-- <ul class="opts list-inline"> -->
            <li>
                <a id="{{ meetingroom.id }}" href="javascript:void(0)" class="post tool delete">
                <span class="glyphicon glyphicon-minus"></span></a>
            </li>
        {% endfor %}
    {% else %}
        <li>
            <div class="meetingroom">
                <h2 class="meetingroom-name">系统中没有会议室！</h2>
            </div>
        <li>
    {% endif %}
    <li>
        <a id="{{ meetingroom.id }}" href="javascript:void(0)" class="post tool add">
        <span class="glyphicon glyphicon-plus"></span></a>
    </li>
</ul>
{% endblock %}

meeting/templates/meeting/submit_success.html
{% extends "meeting/base.html" %}

{% block body %}
<p>提交成功！请等待审批！</p>
{% endblock %}